In [19]:
#Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

array = np.random.rand(10,1);
print(array);

np.mean(array)

[[0.59112656]
 [0.42993269]
 [0.66869353]
 [0.38484557]
 [0.51882205]
 [0.20953443]
 [0.07052012]
 [0.76983408]
 [0.63271677]
 [0.30941742]]


0.4585443220594515

In [25]:
#Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

array1 = np.random.rand(20,1)
print(array1)

[[0.11511091]
 [0.62295947]
 [0.45016676]
 [0.78463388]
 [0.21656154]
 [0.31410428]
 [0.20383843]
 [0.50834525]
 [0.63699594]
 [0.15749442]
 [0.7294833 ]
 [0.94027734]
 [0.31608645]
 [0.85895358]
 [0.10397375]
 [0.02121713]
 [0.58920874]
 [0.34033319]
 [0.12414343]
 [0.39465235]]


In [26]:
np.var(array1)

0.07215521906641698

In [27]:
np.std(array1)

0.2686172352370878

In [13]:
# Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

A = np.random.rand(10,20)
B = np.random.rand(20,25)

C = np.matmul(A,B)
print(C)

[[6.07530987 4.91123312 6.14427939 4.66540392 6.3602423  6.51142875
  7.26140796 5.24794393 6.88924109 7.61462358 5.39426586 6.99858818
  5.95441491 5.09966108 6.6307064  5.91318337 6.26160858 6.65118177
  6.16353807 5.89318909 7.52201108 5.04994317 6.54651887 5.69532693
  7.39835517]
 [3.43960666 3.5975414  3.71261679 3.08287147 4.81602817 3.60140554
  4.53145295 3.31448117 4.08579448 4.78971197 3.66213751 4.9590835
  4.09420774 3.94040394 4.37661091 3.52066932 3.45299128 3.16207229
  3.70644345 4.18266968 4.38282592 3.60884988 3.89983831 4.15159048
  4.80451368]
 [4.88179839 4.80149507 5.3382542  3.83431096 5.55013823 5.44164235
  6.21410928 4.62458181 5.66063043 6.59068599 5.07998512 5.37567779
  5.45351202 5.08060062 5.52048397 4.35817087 5.16930111 5.65361112
  5.28400709 5.28322288 6.3715775  4.2818121  5.83444013 5.34475103
  6.28495084]
 [6.0505408  6.12463826 7.36206845 4.81768269 7.04358436 6.63191161
  7.64359834 5.39531401 7.03405189 8.56027774 5.92902002 6.99800385
  6.849

In [14]:
np.sum(C)

1304.7842980360485

In [28]:
# Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

#f(x)=1 / (1 + exp(-x)) 
#Apply this function to each element of A and print the new array holding the value the function returns
#Example:

#a=[a1,a2,a3]   
#n(new array to be printed )=[ f(a1), f(a2), f(a3)]

A = np.random.rand(10,1)
print (A)

def func(x):
    return (1 / (1 + np.exp(-x)))
    
function = np.apply_along_axis(func, 0, A)
print(function)

[[0.55784014]
 [0.27935915]
 [0.93013335]
 [0.35968878]
 [0.54837057]
 [0.81986775]
 [0.08552129]
 [0.54495418]
 [0.5116074 ]
 [0.77724183]]
[[0.63595264]
 [0.5693891 ]
 [0.71710234]
 [0.5889651 ]
 [0.63375747]
 [0.69420827]
 [0.5213673 ]
 [0.63296413]
 [0.62518321]
 [0.68508536]]
