In [1]:
'''
 Q1. Import MNIST dataset from sklearn. 
     Save data and targets in variables X and Y respectively. 
'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits 
digit = load_digits()
x=(digit.data)
print(x)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [2]:
y=(digit.target)
print(y)

[0 1 2 ... 8 9 8]


In [3]:
#Q2. Perform feature scaling.
from sklearn.preprocessing import StandardScaler
x_SS=StandardScaler().fit_transform(x)
print(x_SS)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


In [4]:
#Q3. Split data into training and testing sets. 
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x_SS , y ,test_size = 0.4, random_state = 20)

In [5]:
#Q4. Perform PCA. Take any value for components. 
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.96 )
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
print(pca.explained_variance_ratio_)

[0.12163885 0.09123035 0.08472444 0.06388294 0.0494201  0.04282851
 0.04102182 0.03786929 0.03517134 0.02972145 0.02839352 0.02687796
 0.02477528 0.02439225 0.02168395 0.01990376 0.01790314 0.01690855
 0.01542958 0.01458062 0.01398432 0.01166788 0.01033306 0.00984864
 0.0093835  0.00906151 0.00857963 0.00791684 0.0076653  0.00728933
 0.00700228 0.00653761 0.00626391 0.00590292 0.00537454 0.00497408
 0.00438788 0.0042681  0.00408694 0.00385854 0.0034617 ]


In [6]:
#Q5. Perform classification (logistic regression).
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train , y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [7]:
'''
Q6.  Print the following:
        a. Accuracy score
        b. Confusion Matrix
        c. Classification Report
''' 
prediction = log.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , prediction))

0.9541029207232267


In [8]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test , prediction))

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  1  0  0  0  0  1  1]
 [ 0  0 63  0  0  0  0  0  0  0]
 [ 0  0  0 73  0  3  0  1  3  0]
 [ 0  1  0  0 72  0  0  1  0  1]
 [ 1  0  0  0  0 70  0  0  0  0]
 [ 0  0  0  0  2  0 69  0  0  0]
 [ 0  0  0  1  0  0  0 78  0  1]
 [ 0  2  0  0  0  1  1  1 58  1]
 [ 0  1  0  0  0  1  0  1  6 68]]


In [9]:
from sklearn.metrics import classification_report
print(classification_report(y_test , prediction,labels = None, digits = 3))

             precision    recall  f1-score   support

          0      0.984     1.000     0.992        63
          1      0.947     0.960     0.954        75
          2      1.000     1.000     1.000        63
          3      0.973     0.912     0.942        80
          4      0.973     0.960     0.966        75
          5      0.933     0.986     0.959        71
          6      0.986     0.972     0.979        71
          7      0.951     0.975     0.963        80
          8      0.853     0.906     0.879        64
          9      0.944     0.883     0.913        77

avg / total      0.955     0.954     0.954       719

