In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#Q1. Import the dataset from sklearn.
dataset = load_digits()
print(dataset)

{'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16

In [4]:
#Q2. Save X(features) and y(target) as dataframes. X is np.array(mnist.data) and y is mnist.target.
feature = pd.DataFrame(dataset.data)
print(feature.head())
target=pd.DataFrame(dataset.target)
print(target.head())

    0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]
   0
0  0
1  1
2  2
3  3
4  4


In [5]:
#Q3. Split the dataset into training and testing sets. 
X=feature
Y=target
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=30)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1203, 64)
(1203, 1)
(594, 64)
(594, 1)


In [6]:
#Q4. Use Logistic Regression. 
reg = LogisticRegression()
reg.fit(X_train,Y_train)
pred =reg.predict(X_test)

C:\Users\kakkaryukta\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
# Q5. Print the following:
#        a. Classification accuracy
#        b. Logarithmic loss
#        c. R2 metrics
#        d. Mean absolute error
#       e. Mean squared error
#       f. Confusion matrix
#        g. Classification report

from sklearn.metrics import classification_report,confusion_matrix,log_loss,mean_absolute_error,mean_squared_error,accuracy_score
print(accuracy_score(Y_test,pred))

0.9545454545454546


In [8]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,r2_score,mean_absolute_error,mean_squared_error
print(r2_score(Y_test,pred))

0.8507365711643946


In [9]:
print(mean_absolute_error(Y_test,pred))

0.21548821548821548


In [10]:
print(mean_squared_error(Y_test,pred))

1.2188552188552189


In [11]:
print(confusion_matrix(Y_test,pred))

[[61  0  0  0  0  0  0  1  0  0]
 [ 0 55  0  1  1  0  1  0  3  1]
 [ 0  0 68  0  0  0  0  0  0  0]
 [ 0  0  1 44  0  1  0  0  1  1]
 [ 0  0  0  0 65  0  0  0  0  1]
 [ 0  1  1  0  0 58  0  1  0  1]
 [ 0  0  0  0  0  0 59  0  1  0]
 [ 0  0  0  0  0  0  0 55  0  0]
 [ 0  3  1  2  0  0  0  0 50  0]
 [ 0  0  0  1  0  1  0  0  1 52]]


In [12]:
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        62
          1       0.93      0.89      0.91        62
          2       0.96      1.00      0.98        68
          3       0.92      0.92      0.92        48
          4       0.98      0.98      0.98        66
          5       0.97      0.94      0.95        62
          6       0.98      0.98      0.98        60
          7       0.96      1.00      0.98        55
          8       0.89      0.89      0.89        56
          9       0.93      0.95      0.94        55

avg / total       0.95      0.95      0.95       594

